FROM gcr.io/prysmaticlabs/prysm/validator:((prysm_version)) AS prysm-orig
FROM debian
RUN apt-get update && apt-get -y install curl telnet
COPY --from=prysm-orig /app/validator/validator /app/validator/validator
COPY entrypoint.sh /app
ENTRYPOINT "/app/entrypoint.sh"
