FROM gcr.io/prysmaticlabs/prysm/beacon-chain:((prysm_version)) AS prysm-orig
FROM debian
RUN apt-get update && apt-get -y install curl
COPY --from=prysm-orig /app/cmd/beacon-chain/beacon-chain.runfiles/prysm/cmd/beacon-chain/beacon-chain_/beacon-chain /app/
COPY entrypoint.sh /app
ENTRYPOINT "/app/entrypoint.sh"
